use_frameworks!

platform :ios, '8.0'

target 'SHSecurityTool_Example' do
  pod 'SHSecurityTool', :path => '../'

  target 'SHSecurityTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
