use_frameworks!

platform :ios, '8.0'

target 'SHSecurityTool_Example' do
  pod 'SHSecurityTool', :path => '../'
  
  #由于依赖的SHTool在更上一层的文件中，所以需要../../
  pod 'SHTool', :path => '../../SHTool'

  target 'SHSecurityTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
